### PR TITLE
[skin.madnox] 20.11.23

### PR DESCRIPTION
**Pull request by mistervee**
- Initial commit

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by MikeSiLVO** [comment]
@ronie I can't respond to your PM lol

Says you have it disabled.

**Comment by MikeSiLVO** [comment]
I have no issues at all tho 🙂

**Comment by ronie** [comment]
@mikesilvo164 thanx, all i wanted to know :-)

**Comment by ronie** [comment]
@mistervee thanx for submitting your skin to the addon repo!
it's always great to get new skins in our repo.

as with all new submissions, there are a few minor issues that need to be fixed before it can be added...

1) please remove the BOM (byte order mark) at the start of these files:
script-embuary-person.xml
script-embuary-image.xml


2) please limit the number of included screenshots to 10
(and update the assets tag in your addon.xml file accordingly)


3) please use lang="en_GB" for the summary / description / disclaimer in your addon.xml file


4) please fix these conditions (brackets do not match) in Includes_InfoDialogs.xml on line 850:
!String.IsEmpty(ListItem.Property(Artist_Type)
String.IsEqual(ListItem.DBTYPE,artist))


should you have any questions, comments or need help, just let me know!

**Comment by mistervee** [comment]
@ronie 
Thanks. I have made the changes but am not sure how to force push the changes so there is only one commit.

**Comment by mistervee** [comment]
Found this in the wiki
https://kodi.wiki/view/HOW-TO:Update_a_pull_request_to_an_official_addon_repository_on_GitHub

Hopefully it works

**Comment by mistervee** [comment]
@ronie 
Seems like it worked, issues are now fixed.

**Comment by ronie** [comment]
great, thx!

**Comment by mistervee** [comment]
TY @ronie

**Pull request merged**
