### PR TITLE
[skin.copacetic-1.2.2~nexus]

### PR DESCRIPTION
**Pull request by realcopacetic**
### Description
**1.2.2**
- Non-breaking changes to keep code in sync with Omega
- Cleaned some expressions governing Light theme and artwork backgrounds to simplify complex scenarios when several transparent windows are open on top of each other
- Removed flash of light background when transitioning from fullscreen artwork background to fullscreen artwork infoscreen.
- Removed some obsolete parameters
- Fixed some instances when the primary colour was incorrectly used instead of the secondary colour on light background views when Light theme selected, causing things like scrollbars to be shown as white on white instead of black on white
- Fixed a fadediffuse bug in the embedded list artwork mask used on Strip view
- Fixed the missing Ken Burns effect from Billboard and List views with fullscreen artwork

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by realcopacetic** [comment]
Here we are again @ronie with another failure, although for a different reason it seems like this time. I was going to submit to the omega repo as well, today, but I really want to get to the bottom of why this keeps failing

**Comment by ronie** [comment]
the error did not seem related to your skin,
so i re-ran the addon checker and now it fails at a different point.
it does not like the version number you use in addon.xml.

could you please stick to a simple numeric X.Y.Z version number?

**Comment by realcopacetic** [comment]
Ahh sorry about that @ronie I must have misunderstood the documentation on version numbering, I've removed that and it seems to have done the trick!

**Comment by ronie** [comment]
thx!

**Pull request merged**
