### PR TITLE
[skin.amber] 3.1.4

### PR DESCRIPTION
**Pull request by bartolomesoriano**
### Description
Skin Amber updated for Leia
### Checklist:
- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by ronie** [comment]
great, thanx for reviving the amber skin!

i've reviewed your skin and have a list of a few items that require your attention:

please change the forum link in your addon.xml to http**s**://
`<forum>http://forum.kodi.tv/forumdisplay.php?fid=203</forum>`

rename DialogPVRGuideOSD.xml -> DialogPVRChannelGuide.xml
see: https://forum.kodi.tv/showthread.php?tid=298565&pid=2550314#pid2550314

Variable not defined: DefPosCustHomeVis
SkinSettings.xml: line 966

Variable not defined: AudioDSPItemDescription
DialogAudioDSPManager.xml: line 432
you can remove anything DSP relasted from your skin, as it is no longer supported
see: https://forum.kodi.tv/showthread.php?tid=298565&pid=2785902#pid2785902

Font not defined: shelf_label (case sensitive issue)
Includes_Media.xml: line 326
Includes_Media.xml: line 336
Includes_Media.xml: line 381
Includes_Media.xml: line 391
Includes_Media.xml: line 442
Includes_Media.xml: line 454
Includes_Media.xml: line 503
Includes_Media.xml: line 515
Includes_Media.xml: line 524
Includes_Media.xml: line 538

Label not localized: Signal
DialogFullScreenInfo.xml: line 97

Label not defined: 161
DialogPVRRadioRDSInfo.xml: line 48
DialogPVRRadioRDSInfo.xml: line 119
DialogPVRRadioRDSInfo.xml: line 170
DialogPVRRadioRDSInfo.xml: line 194
DialogPVRRadioRDSInfo.xml: line 219
DialogPVRRadioRDSInfo.xml: line 295

Label not defined: 15020
DialogAudioDSPManager.xml: line 19

Label not defined: 15064
DialogAudioDSPManager.xml: line 447

Includes_Variables.xml:	line 757
Error parsing boolean expression [window.isactive(mypvrchannels.xml) | window.isactive(mypvrguide.xml) | window.isactive(mypvrrecordings.xml)] + !string.isempty(listitem.plot) + !string.isequal($info[listitem.episodename],$info[listitem.plot])

DialogPictureInfo.xml
ERROR: Control 60 in window 10139 has been asked to focus, but it can't
(you can either set the default focus to the list, or make sure the scrollbar is always visible)


if you have any questions, or need help, just let me know!

**Comment by bartolomesoriano** [comment]
@ronie , thank you! Some of those stem from me not touching that part of the code at all.  I have fixed all except for the one in Includes_Variables.xml, since I cannot figure out what is wrong with that line of code!

So, how do I modify this PR with the updated files? I am not great with Git and I use it through SmartGit for Windows.  Thanks for your help.

**Comment by bartolomesoriano** [comment]
@ronie , I guess I did not do it right and created another commit instead of squashing the changes into the existing commit.  Should I close this pull request and create a new one that has all of the fixed issues?

**Comment by Rechi** [comment]
To fix your pull request execute the following commands (origin is your repo, upstream is the xbmc repo)

```
git fetch upstream
git checkout leia
git reset --hard upstream/leia
git checkout origin/leia -- skin.amber/
git commit -m '[skin.amber] 3.1.4'
git push -f origin leia
```

**Comment by bartolomesoriano** [comment]
> To fix your pull request execute the following commands (origin is your repo, upstream is the xbmc repo)
> 
> ```
> git fetch upstream
> git checkout leia
> git reset --hard upstream/leia
> git checkout origin/leia -- skin.amber/
> git commit -m '[skin.amber] 3.1.4'
> git push -f origin leia
> ```

@Rechi , I tried this, but I got an error on the git commit -m command, due to the space between ] and 3.1.4, so I did the command without the space.  Is this now what is expected?

Should I close this pull request and try again? I am sorry for being so inexperienced with Git. Thank you for your help.

**Comment by bartolomesoriano** [comment]
@Rechi , @ronie there is one file I renamed and 1 file I deleted as per @ronie 's instructions, but both the renamed file and the file without renaming are present in the commit, as well as the file I deleted.  I could not figure out how to fix this.

**Comment by ronie** [comment]
>  I have fixed all except for the one in Includes_Variables.xml, since I cannot figure out what is wrong with that line of code!

the correct way to do a string compare between infolabels is:
!String.IsEqual(listitem.episodename, listitem.plot)

so no need to wrap them in a $INFO[] tag
see: https://kodi.wiki/view/List_of_boolean_conditions#String



> the renamed file and the file without renaming are present in the commit, as well as the file I deleted

i'm not familiar with SmartGit, but you need to add those files to your commit:
```
git add DialogPVRGuideOSD.xml
git add DialogAudioDSPManager.xml
git commit -m "remove files"
```

**Comment by bartolomesoriano** [comment]
> > I have fixed all except for the one in Includes_Variables.xml, since I cannot figure out what is wrong with that line of code!
> 
> the correct way to do a string compare between infolabels is:
> !String.IsEqual(listitem.episodename, listitem.plot)
> 
> so no need to wrap them in a $INFO[] tag
> see: https://kodi.wiki/view/List_of_boolean_conditions#String
> 
> > the renamed file and the file without renaming are present in the commit, as well as the file I deleted
> 
> i'm not familiar with SmartGit, but you need to add those files to your commit:
> 
> ```
> git add DialogPVRGuideOSD.xml
> git add DialogAudioDSPManager.xml
> git commit -m "remove files"
> ```

@ronie , thank you! I will fix as soon as I get home.  The command is git add or git rm? Am I not supposed to be removing those files from the commit?

**Pull request closed without merging**
