### PR TITLE
[skin.aeon.nox.silvo] v9.99.3

### PR DESCRIPTION
**Pull request by MikeSiLVO**
### Description
Fixes and changes, including DialogVideoVersions --> DialogVideoManager 

Thanks :)

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by MikeSiLVO** [comment]
Hey ronie 👋 
Not sure if this should be merged yet or not. The changes for DialogVideoVersions --> DialogVideoManager wouldn't work on Beta 2 and not sure when Beta 3 or RC will come. What do you think?

**Comment by ronie** [comment]
although i don't know when the next beta will be released, i think i should wait with merging in this case.
but ultimately it's up to you ofc.

you ping me here whenever you think it should go in.

**Comment by MikeSiLVO** [comment]
Ok dokie. Will wait for the next Kodi release.
Thanks ronie!

I will ping but if you'd prefer that I close/delete this PR until I can reopen it at a later date, let me know 😃

**Comment by MikeSiLVO** [comment]
@ronie since Beta 3 is now released it would be great if you could merge this to Omega repo when you have time.

Thanks :)

**Comment by ronie** [comment]
thx!

**Pull request merged**
