### PR TITLE
[skin.copacetic 1.1.4]

### PR DESCRIPTION
**Pull request by realcopacetic**
### Description
A fix for the dependency error currently preventing people from installing the skin via the official repo (downgraded the requirement for script.copacetic.helper to match what is currently in the official repo)

**1.1.4**
- Added studio flag for Neon
- Changed navigation on home menu to wrap on additional direction press so at the end of the list if you press right again, it will take you back to the list. And at the start, pressing left will take you to the end.
- Widgets will also wrap around on second press if there is more than one item in the container.
- Optimised screenshots and icons in /resources and /extras/skinsettings folders.
- Fixed several infoscreen widgets that weren't working correctly when the source of the list item was a plugin and themoviedbhelper was installed and being used to populate the plugin.

**1.1.3**
- Fixed issue introduced in 1.1.1 with wrong multiart displaying on some widgets
- Fixed issue introduced in 1.1.2 where disabled/empty widgets could not be changed in skinsettings 

**1.1.2**
- Fixed issue affecting wrong artwork sometimes being shown in widgets using grid and fanart layout when scrolling backwards.
- Fixed multiart behaviour on list/billboard view when main container loses focus
- Fixed artwork displayed on secondary lists for list/billboard view when multiart visible
- Refined user experience of widget settings screen. It should now be easier to see how to configure widgets
- Removed inactive icons from dialogselect window when accessed via skinsettings

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by realcopacetic** [comment]
hi @ronie hope you're well. Do you know what the following error means in the new addon-checker added for skins?

`ERROR: ./skin.copacetic/media/flags/rating/MPAA_NC-17.png is marked as stand-alone executable`

The automated scan flagged hundreds of these in my skin but I don't understand what it means to know how to fix it.

**Comment by realcopacetic** [comment]
> hi @ronie hope you're well. Do you know what the following error means in the new addon-checker added for skins?
> 
> `ERROR: ./skin.copacetic/media/flags/rating/MPAA_NC-17.png is marked as stand-alone executable`
> 
> The automated scan flagged hundreds of these in my skin but I don't understand what it means to know how to fix it.

hi @enen92 I think this may have been better addressed to you as I just saw you were the one who added the new checkers. Can you shed light on this error please?

**Comment by enen92** [comment]
@realcopacetic that means the file is set as an executable (which can be seen as a security flaw). See https://adamj.eu/tech/2023/01/31/git-add-remove-execute-permissions/ to see how to remove it

**Comment by realcopacetic** [comment]
thanks @enen92 I will try and figure this out.

**Pull request closed without merging**
