### PR TITLE
[skin.aeon.nox.silvo] v7.0.7

### PR DESCRIPTION
**Pull request by mikesilvo164**
### Description
-   Fix Live TV OSD button focus when unable to pause
-   Fixes to DialogSelect
-   Fix no items in Ask Default Background selection on new installs
-   Drop Skin Helper Widgets for favorites and use favourites:// path instead
-   Update and add some missing icons
-   Fix Netherlands rating classification images
-   Update and re-design PVR Group Manager

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by mikesilvo164** [comment]
@ronie Forced pushed to delete the added empty language comments from @txtranslation 
I should remove that for the PR's right or can I ignore it for next time?

@gade01 Not sure if you're able to but is there any chance to have the automatic language correction from transifex not add the empty line comments?

**Comment by mikesilvo164** [comment]
@ronie I also wanted to double check I am using the license correctly for the icons used in the skin that are from Estuary.

[LICENSE](https://github.com/mikesilvo164/Aeon-Nox-SiLVO/blob/master/LICENSE.txt#L9)

**Comment by ronie** [comment]
empty lines comments are ok, but the syntax was invalid.
there needs to be a space between the hash and the text.
`# valid comment`
`#invalid comment`

the license is ok.

**Comment by ronie** [comment]
thx!

**Comment by gade01** [comment]
@ronie @mikesilvo164 

I'll check why comments are added without the blank space.

That absolutely has to be changed for all skins.

**Comment by gade01** [comment]
@ronie @mikesilvo164 

I just got this answer from Attila:

> The "incorrect" fotmat is what we want here. This is a workaround that there is no commend defined in the PO format that is NOT connected to any of the entries. If we make a correctly formated entry it will be connected to the following entry and vissible in transifex at that entry. I guess the lack of non entry comments comes from the fact that gettext originally machine generates the Po files from the source code so these type of comments are not used there. So format is ok like this. It is just a help for devs to find unused numbers.

**Comment by ronie** [comment]
i have little knowledge of our travis configuration...
this might be one for @Rechi

**Pull request merged**
