### PR TITLE
[skin.confluence] 4.6.9

### PR DESCRIPTION
**Pull request by DaVukovic**
### Description

Skin Confluence update to version 4.6.9

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by ronie** [comment]
can you remove the BOM at the start of these files:
found BOM. File: ../addon-repo/skins/skin.confluence/720p/IncludesHomeMenuItems.xml
found BOM. File: ../addon-repo/skins/skin.confluence/720p/ViewsVideoLibrary.xml


also, there's no string with id 416 in the Kodi language file anymore:
Label not defined: 416
720p/ViewsVideoLibrary.xml: line 1477

Label not defined: 416
720p/ViewsVideoLibrary.xml: line 1610

**Comment by DaVukovic** [comment]
Hope this is correct now ;)

**Comment by ronie** [comment]
thx!

**Comment by Rechi** [comment]
Why was this merged with failing CI?

**Comment by ronie** [comment]
@Rechi see the discussion here:
https://github.com/xbmc/repo-skins/pull/262

**Comment by Rechi** [comment]
The po files is invalid, as reported, see syntax description at https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html.

**Pull request merged**
