### PR TITLE
[skin.amber] v3.50.02

### PR DESCRIPTION
**Pull request by MikeSiLVO**
### Description

Updating Amber for Nexus. With bartolomesoriano's permission.

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by MikeSiLVO** [comment]
I see the error but I do not see where the issue actually is. 
Any pointers would be appreciated since it looks like a zipped after the fact problem.

Thanks.

**Comment by ronie** [comment]
doesn't look related to your skin, so let's ignore it for now :)

came across a few things to check though:

Variable not defined: EpisodeTitleVar
1080i/View_502_RightList.xml: line 2035

Variable not defined: TitleColorVar
1080i/View_502_RightList.xml: line 2037

Variable not defined: InfoWallBottomLabel1Var
1080i/View_502_RightList.xml: line 2046

Variable not defined: ListAlbumVar
1080i/View_502_RightList.xml: line 2056

Variable not defined: TitleColorVar
1080i/View_502_RightList.xml: line 2084

Variable not defined: TitleColorVar
1080i/View_502_RightList.xml: line 2096

Variable not defined: InfoWallBottomLabel1Var
1080i/View_502_RightList.xml: line 2107

Variable not defined: InfoWallTextboxVar
1080i/View_502_RightList.xml: line 2116

**Comment by MikeSiLVO** [comment]
I thought I commented all of those out. I'll take a look when I get home 😄  

I wasn't sure if Bart was in the middle of adapting the code to Amber or not so didn't want to just delete it.

**Comment by ronie** [comment]
ah that could be, my automated script might have missed that.

**Comment by ronie** [comment]
nope, they are still there.

**Comment by MikeSiLVO** [comment]
I can’t  double check the PR files. GitHub mobile is crap lol

The entire include should be commented out

https://github.com/MikeSiLVO/skin.amber/blob/master/1080i/View_502_RightList.xml#L2016

**Comment by ronie** [comment]
confirmed, must've been a brainfart.

**Comment by MikeSiLVO** [comment]
Thanks, ronie 😃

**Pull request merged**
