### PR TITLE
[skin.metropolis] 3.4.3

### PR DESCRIPTION
**Pull request by jingai**
### Description
- Show year/duration/etc in List Fanart view.
- Add show path option for DialogMusicInfo.
- Fix ratings/path in DialogVideoInfo.
- Fix black box behind episode thumb in List view.
- Add Privacy Policy to System Info.
- Fix Smart Playlist Editor.
- Minor fixes for Krypton final.
- Update fonts.
- Update language files from Transifex.
### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

### CODE REVIEW

**Comment by ronie** [comment]
thx!

**Comment by jingai** [comment]
Is it normal for this to take a while to show up on the mirrors, or is there something wrong?

**Comment by ronie** [comment]
nope, not normal to take this long.

ping @MartijnKaijser

**Comment by MartijnKaijser** [comment]
Well if you guys overlooked the fact there was no actual version bump in addon.xml there's nothing i can do about that 😆

**Comment by jingai** [comment]
Ah shoot.. lol

**Pull request merged**
