### PR TITLE
skin.copacetic 1.0.3

### PR DESCRIPTION
**Pull request by realcopacetic**
### Description
skin.copacetic 1.0.3 adds weblate integration and translations for French/Spanish, plus some minor bug fixes as detailed in the changelog here --> [Readme.md](https://github.com/realcopacetic/skin.copacetic/blob/master/README.md)

### Checklist:
- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by realcopacetic** [comment]
hi, I have a question now that skin.copacetic is in the official nexus repo. It has 2 dependency addons that I created (script.copacetic.helper and resource.fonts.copacetic). I submitted those at the same time but they haven't been approved. Meaning, that if anyone  tries to install this skin from the official repo without my own repository installed, it will fail. What do you advise in this situation? Removing skin.copacetic until it has been decided if those addons will be approved/merged? Or is there a better solution? 

I was going to try and get a new page set up for the skin in the forum under 'skins support' but it doesn't seem like a good idea to bring attention to it while it can't be installed properly.

These are the open PRs by the way: 

xbmc/repo-resources --> https://github.com/xbmc/repo-resources/pull/392#issue-1670827688
xbmc/repo-scripts --> https://github.com/xbmc/repo-scripts/pull/2441#issue-1670821817

**Comment by ronie** [comment]
looks like those two addons are close to being merged, so pulling the skin from the repo isn't needed imo.

i'll merge 1.0.3 once those two addons get in.

**Comment by realcopacetic** [comment]
Thanks @ronie

**Comment by realcopacetic** [comment]
> looks like those two addons are close to being merged, so pulling the skin from the repo isn't needed imo.
> 
> i'll merge 1.0.3 once those two addons get in.

Hi @ronie the addon script was merged, but the resource addon won't be added for some time due to an issue with the Addon checker --> see comment from @romanvm here https://github.com/xbmc/repo-resources/pull/392#issuecomment-1540945877

So I've removed the dependency for now and will advise people who need CJK font support on the forum to use the version of the skin in my repo which has the extra fontset in place and the extra addon.

Are you able to merge this one so the skin can be downloaded from the repo? Thanks!

**Comment by ronie** [comment]
sure thing, there she goes...

**Comment by realcopacetic** [comment]
Woohoo, thanks @ronie

**Pull request merged**
