### PR TITLE
[skin.adonic] 1.0.0

### PR DESCRIPTION
**Pull request by BADMS**
Description
Checklist:

    [X] My code follows the add-on rules and piracy stance of this project.
    [X] I have read the CONTRIBUTING document
    [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :

    Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
    add-on development wiki page.
    Kodi pydocs provide information about the Python API
    PEP8 codingstyle which is considered best practice but not mandatory.
    This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at Codacy. You can create your own account as well to continuously monitor your python coding before submitting to repo.
    Development questions can be asked in the add-on development section on the Kodi forum.

New skin, I need to get the ball rolling and get it on the 'checking in' process, else I never will!! Thanks!

### CODE REVIEW

**Comment by BADMS** [comment]
Sorry about extra commit, hopefully you can squash!!

**Comment by BigNoid** [comment]
Thx for submitting your skin to the Kodi repository, it's always nice to see a new skin!
I've only found a few things:

- Please remove XML/script-skinshortcuts-includes.xml
- Window ID not defined: 1133 - XML/Includes.xml: line 555
- Window ID not defined: 1120 - XML/Includes_Player.xml: line 318
- Window ID not defined: 1128 - XML/SkinSettings.xml: line 216
- invalid attribute for include: name - XML/DialogKeyboard.xml: line 473
- Font not defined: TinyBold - XML/Includes.xml: line 1765
- ERROR: Window Translator: Can't find window programsettings
- Include not defined: MusicLowList - XML/MyPics.xml: line 60

**Comment by BADMS** [comment]
Thanks! Hopefully all fixed, let's see how this goes .. 💃

**Comment by BigNoid** [comment]
Thx, I will take another look. Meanwhile I missed the Horseferry fonts. According to [this](http://brody-associates.com/projects/channel-4) it doesn't seem it's freely redistributable and if it is, it's missing a license file.

**Comment by BADMS** [comment]
Thanks BigNoid, have removed Horseferry, not 100% sure about the license as it wasn't from there.

**Comment by BigNoid** [comment]
Thx!

**Comment by BADMS** [comment]
Excellent, thank you 👍

**Comment by MartijnKaijser** [comment]
@BADMS please add http://forum.kodi.tv/forumdisplay.php?fid=275   as forum link in addon.xml for next update. Thx

**Pull request merged**
