### PR TITLE
Commit for case sensitive issue

### PR DESCRIPTION
**Pull request by MikeSiLVO**
### Description
Testing out the fix for my issue

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by MikeSiLVO** [comment]
@ronie 
Mind taking a look at this? 
Maybe you can point me in the right direction on what to do if this isn't the correct approach. It causes issues on my forked repo as well as just a clone of the main repo.

**Comment by gade01** [comment]
@MikeSiLVO 
What is the issue with this file for TetradUI skin?
Removing it will break the skin.

**Comment by MikeSiLVO** [comment]
I'm not removing it, something with the file name change and systems that are case insensitive like Windows causes issues for me. The file just won't go away and this was the solution I found when googling.

includesVariables.xml --> IncludesVariables.xml.

I added some [screenshots](https://github.com/xbmc/repo-skins/pull/390#issuecomment-1494795755) of what I encounter when dealing with the Nexus Repo. I have no issues on any others.

The file is here https://github.com/MikeSiLVO/repo-skins/blob/silvo_nexus/skin.tetradui/xml/IncludesVariables.xml and should be the same one in the Kodi repository. Is it not?

**Comment by ronie** [comment]
ah i see now. TetradUI contains both  IncludesVariables.xml and includesVariables.xml.

hadn't noticed it since i'm on linux, but for windows this will lead to problems.

@MikeSiLVO i think removing includesVariables.xml is correct, since you only need IncludesVariables.xml?

**Comment by gade01** [comment]
Ah, I didn't know both files were present in the nexus repo.
If they're identical, removing includesVariables.xml shouldn't be a problem at all.
That seems like the correct solution :)

Thanks guys for sorting this out.

**Comment by MikeSiLVO** [comment]
> ah i see now. TetradUI contains both IncludesVariables.xml and includesVariables.xml.
> 
> hadn't noticed it since i'm on linux, but for windows this will lead to problems.
> 
> @MikeSiLVO i think removing includesVariables.xml is correct, since you only need IncludesVariables.xml?

It's not my Skin but I assume it is needed as IncludesVariables.xml as that is the [filename being imported in the includes.xml](https://github.com/xbmc/repo-skins/blob/nexus/skin.tetradui/xml/includes.xml#L8) 😄

**Comment by ronie** [comment]
ok then, lets get this merged.

**Pull request merged**
