### PR TITLE
[skin.phenomenal] 4.2.2

### PR DESCRIPTION
**Pull request by Rechi**
@MartijnKaijser just bump version to get screenshots generated after the generator script was fixed.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
Does the author the skin know this because we never just bump on our own

**Comment by Rechi** [comment]
not yet, I try to contact the author.

**Comment by tomer953** [comment]
No problem. Thanks for letting me know.

**Comment by Rechi** [comment]
@MartijnKaijser can be merged now

**Comment by ronie** [comment]
could someone please enlighten me what this is all about? :-)

**Comment by Rechi** [comment]
@ronie https://github.com/tamland/xbmc-repo-gen/pull/2
`_screenshots` directory was completely excluded during preparing add-ons for our mirrors.
For this add-on it means no files at http://mirrors.kodi.tv/addons/krypton/skin.phenomenal/_screenshots/ which produces 404s, missing files in the zip file, and no preview of screenshots in kodi.

**Comment by ronie** [comment]
ah, ok. got it, thx!

there's one other skin that uses a _screenshots folder: skin.titan
ping @marcelveldt mind doing a version bump for your skin?

**Comment by marcelveldt** [comment]
@ronie, will do so tonight, thanks

**Comment by Rechi** [comment]
@ronie @marcelveldt this is only an issue if the files are listed in http://kodi.wiki/view/addon.xml#.3Cassets.3E, because then kodi tries to load them in the add-on installation/preview window.
So there is no need to bump version, as you haven't them listed in `assets` and that's also the reason I haven't spotted that your skin also has a `_screenshots` directory.

**Comment by ronie** [comment]
perhaps you're looking at the wrong branch?

titan does use the assets tag: https://github.com/marcelveldt/skin.titan/blob/krypton/addon.xml#L28-L41

and has an empty _screenshots folder on our mirrors:
http://mirrors.kodi.tv/addons/krypton/skin.titan/_screenshots/

**Comment by Rechi** [comment]
sorry just ignore my previous comment.

I spotted the issue 5 days ago and at that time only `skin.phenomenal` was effected. Meanwhile `skin.titan` was updated, but I haven't check again if new/updated add-ons got affected.

**Comment by marcelveldt** [comment]
@ronie, sorry for the late reply. I've bumped the version of the skin on GH.

**Comment by ronie** [comment]
@marcelveldt updated, thx!
https://github.com/xbmc/repo-skins/commit/2cc232145588f85332f61f49067521fd305445b7

**Pull request merged**
