### PR TITLE
[skin.aeon.nox.silvo] v8.0.1

### PR DESCRIPTION
**Pull request by MikeSiLVO**
### Description
- Use Weblate for translations (thanks gade01)
- Fix Embuary error when navigating to a TV Show Season
- Add a clean paused screen option to Video OSD settings
- Re-add script.grab.fanart support
- Fix missing sortby labels
- Add status indicator settings for BigFan
- Fix Rick Dangerous error
- Default letter jump fixes
- Tweak MyFlix info for Episodes
- Fix auto hide OSD options duplicating in other settings

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by ronie** [comment]
thanx for the update!

could you have a look at these two translation issues?

Label in <label> not translated: Direct Kodi search in library
16x9/SkinSettings.xml: line 448


Label not defined: 31586
16x9/custom_1115_VideoOSDSettings.xml: line 82

**Comment by MikeSiLVO** [comment]
Oops, I forgot to add the first one but 31586 is in the po file... 🤔 


NVM I forgot to add the updated po file to the commit 🥴

**Comment by MikeSiLVO** [comment]
Should be all set now 😄

**Comment by ronie** [comment]
thx!

**Pull request merged**
