### PR TITLE
[skin.embuary-leia] 18.8.6

### PR DESCRIPTION
**Pull request by sualfred**
### Description

Version 18.8.7
- remove unwatned pulse effect on sliderex control

Version 18.8.6
- Fixed main menu artwork issues
- Changed genre window because of speed issues on slower devices and with EmbyCon
- Removed previously introduced "Fav. Kodi Movies" and "Fav. Kodi TV Shows" and replaced it with "Watchlist" tag support
- Use DBID for TMDb search
- Added "shuffle" and "repeat" buttons to music OSD
- Added preview toggle in keyboard dialog

Version 18.8.4
- Reload widgets directly after finished DB scan (helper addon)
- Increased delay after last DB item update to reduce not required widget reloads (helper addon)
- Fixed logic error in image cache handling (helper addon)
- Fixed missing resume dialog for Embuary Helper listings and actions
- Added content type and category info label to Embuary Helper nodes
- Enabled episode views for Embuary Helper paths
- Added "Restart Kodi" to shutdown menu for LE/CE
- Fixed "Emby for Kodi addon missing" message in favourites for non Emby setups
- Added TMDb button to fullscreen info dialog
- Added Embuary Helper paths to menu editor dialog
- Switched skin based select dialogs to context menu dialogs
- Hide cast widget if trailer is playing
- Show episode thumb in search results
- Removed episode label duplicate in list view

Version 18.8.1
- Fixed cinema mode
- Fixed some main menu issues
- Filter EmbyCon collections based on parent ID
- Added new favourites movies/shows type for non Emby setups

Version 18.8.0
BREAKING CHANGES
A reset of menus, widgets and hubs is required due code changes. Otherwise you will face issues and bugs. A new setup dialog will do it for you.

- Dropped previous method of Emby library nodes detection and replaced it with a general library nodes approach to support any Kodi tag based system
- Added a new 'mixed' tag hub that will be used for "mixed content" Emby nodes
- Emby nodes like "Homevideos & Photos" must be set manually now
- Added library tag whitelist feature to disable unwanted library tag based hubs
- Added option to rerun the skin setup
- Episode cast list will now return the information based on the episode instead of the TV show
- Fixed logged spamming during playback

Version 18.7.30
- Use auto generated genre thumbnails (first generation can take a few seconds depending on the device)
- Added tags to Slide view and info dialogs for movies and TV shows
- Added genre widget to Emby nodes
- Added "now playing in theaters" and "new movies coming soon" as shipped widgets. By default they are are set to the home screen. Existing setups have to manually assign them. They are available for the home screen and all movies hub.
- Fixed missing Rotten Tomatoes rating in video info dialog
- Fixed widget resetting

Version 18.7.29
- Better slide view performance
- Reworked some skin hacks
- Faster scrolltimes in widgets
- Readded showing video OSD on playback start (was removed by mistake)

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by ronie** [comment]
thanx for the update!


could you have a look at these please:

found BOM: 
script-embuary-image.xml

Variable not defined: Emby.FavMovies
DialogFavourites.xml: line 72

Brackets do not match: [!Skin.HasSetting(HidePosterLabels) | !Window.IsVisible(myvideonav.xml) | $EXP[ForceLabels]
Embuary_Poster_View_51.xml: line 28

Brackets do not match: [!Skin.HasSetting(HidePosterLabels) | !Window.IsVisible(myvideonav.xml) | $EXP[ForceLabels]
Embuary_Poster_View_51.xml: line 42

**Comment by sualfred** [comment]
@ronie 
Thanks, but what do you mean with BOM?

**Comment by ronie** [comment]
Byte Order Mark, or as i would say, an invisible character at the start of the file.
it's not recommended to us a BOM in UTF-8: https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8

**Comment by sualfred** [comment]
Thanks. Dunno how this happend. And never heard of it to be honest. Anyway. Should be be fine now.

**Comment by ronie** [comment]
thx!

**Pull request merged**
