### PR TITLE
[skin.aeon.nox.silvo] v9.0.0

### PR DESCRIPTION
**Pull request by MikeSiLVO**
### Description
[skin.aeon.nox.silvo] v9.0.0

- Kodi v20 Nexus support
- Fix mismatched DialogMusicInfo icons
- Add option to hide the system bars on the main menu
- Add HDR type flags to some views
- Add basic support for MyFavourites.xml
- Fix status indicators not following the setting for MyFlix Landscape
- Rework Settings screen
- Add script.xbmcbackup to optional add-ons
- Add show password button to DialogKeyboard.xml
- Add option to hide budget + revenue from DialogVideoInfo
- Remove references to Artwork Beef
- Fix Live Background overriding SubMenu backgrounds
- Add scrollbar to MyPVRRecordings
- Add Opus mediaflag for audio codec
- Fix InfoWall alternate layout status indicators
- Add solid color backgrounds to fallback options
- Fix navigation issue when in General section of Skin Settings
- Add greyscale versions of colored aspect ratio icons to include missing ratios
- Fix music playlist opening videoplaylists instead of musicplaylists for main and submenus using the main menu customizer
- Add zorder to DialogSubtitles so pause icon/label isn't shown on top when directly calling SubtitleSearch
### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by MikeSiLVO** [comment]
Hoping this can be added when my other PR's get approved 😄 
https://github.com/xbmc/repo-scripts/pull/2404
https://github.com/xbmc/repo-scripts/pull/2403

**Comment by ronie** [comment]
thanx for the update, could you please fix his minor issue:

Include not defined: Hiddenobject
16x9/DialogKeyboard.xml: line 12

**Comment by MikeSiLVO** [comment]
Silly typo
Should be fixed now 😄 

I read in another PR that you might be using a modified version of KodiDevKit to check the skins. Not sure how many changes you have made but I am wondering if you wouldn't mind sharing those changes so I can update my copy as well? I still use it but the checking functions are so far behind that it's a chore to actually check for issues and my Python skills are still terrible 🤣

**Comment by ronie** [comment]
yes, i suffer from the same problem as you. 
i only use it because it's "better than nothing", but it ain't exactly fun scrolling through all the false errors reported.

skin looks good to me now, so please ping me here once those two scripts have been merged.

**Comment by MikeSiLVO** [comment]
Will do :handshake:

**Comment by MikeSiLVO** [comment]
@ronie 
Those scripts have been added to the Kodi repo 😄

**Comment by ronie** [comment]
great, thx!

**Pull request merged**
