### PR TITLE
skin.copacetic 1.0.0 fixes from @ronie

### PR DESCRIPTION
**Pull request by realcopacetic**
Initial repo submission for skin.copacetic

### Description
Initial submission for new skin [Copacetic](http://forum.kodi.tv/showthread.php?tid=232964). Submitting alongside two dependencies, script.copacetic.helper and resource.fonts.copacetic, to the relevant repos.

### Checklist:
- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by ronie** [comment]
nice, always great to see a new skin being submitted to the addon repo.

i had a look at the code and came up with a few things that need fixing:
missing **msgstr** lines in strings.po for these labels:
31211
31216
31600-31603
31900-31914


Variable not defined: List_Scroll_Focus_Color
16x9/DialogTextViewer.xml: line 31


Variable not defined: Progress_Light_Focus_Color
16x9/DialogConfirm.xml: line 37


Variable not defined: Copacetic_Divide
16x9/Variables_Labels_Color.xml: line 171


Font not defined: Main_Menu_unfocused (case sensitive issue)
16x9/Components_Home.xml: line 383


Brackets do not match: !String.IsEqual(Listitem.DBType,tvshow) + !String.IsEqual(Listitem.DBType,season) + !String.IsEqual(Container.FolderPath,Window(movieinformation).Property(ContainerPath_1)
16x9/Content_Infoscreens.xml: line 88

**Comment by realcopacetic** [comment]
> nice, always great to see a new skin being submitted to the addon repo.
> 
> i had a look at the code and came up with a few things that need fixing: missing **msgstr** lines in strings.po for these labels: 31211 31216 31600-31603 31900-31914
> 
> Variable not defined: List_Scroll_Focus_Color 16x9/DialogTextViewer.xml: line 31
> 
> Variable not defined: Progress_Light_Focus_Color 16x9/DialogConfirm.xml: line 37
> 
> Variable not defined: Copacetic_Divide 16x9/Variables_Labels_Color.xml: line 171
> 
> Font not defined: Main_Menu_unfocused (case sensitive issue) 16x9/Components_Home.xml: line 383
> 
> Brackets do not match: !String.IsEqual(Listitem.DBType,tvshow) + !String.IsEqual(Listitem.DBType,season) + !String.IsEqual(Container.FolderPath,Window(movieinformation).Property(ContainerPath_1) 16x9/Content_Infoscreens.xml: line 88

Thanks, I'm embarrased you found these so easily. I thought I had QAd fairly thoroughly, but looking at the list it looks like some of these are things I introduced with some of my last bug fixes. I'll get these updated asap thanks

**Comment by realcopacetic** [comment]
Sorry @ronie I'm not great at github and it wouldn't let me squash the commit with the changes you mentioned into my initial commit. I think due to some sort of issue with the other open pull request (tetradui) being seen as a change on my branch when I cloned it. 

Please let me know if I should close the pull request and submit a new pull request with a single commit including the changes you requested.

**Comment by ronie** [comment]
@realcopacetic github will squash both commits when i merge the pull request.

**Comment by ronie** [comment]
added, thx!

**Comment by realcopacetic** [comment]
Thanks @ronie!

**Pull request merged**
