### PR TITLE
[skin.embuary-leia] 18.7.14

### PR DESCRIPTION
**Pull request by sualfred**
### Description

Version 18.7.14
- Added browseable widget sources to Embuary Helper to make it possible to select/open predefined widgets via addon node
- Added retry logic to Embuary Helper to reduce the amount of dynamic widgets with no content
- Added service restart option to Embuary Helper
- Added option to select the blurring strength
- Added option to hide the player OSD during volume change

Version 18.7.13
- Fixed cinema mode issues by starting from context menu
- Fixed cinema mode issues if previous playback had shuffle enabled
- Force context menu focus on load
- Added context menu separators

Version 18.7.12
- Fixed broken unwatched episodes overlay on season level
- Fixed episode thumb issues
- Added "Play all" and "Shuffle" for shows and seasons (context menu, slide view, info dialog)
- Added PVR channel groups to PVR hub (can be disabled)
- Fixed wrong shadow color values
- Minor rework of the header bar
- Fixed visibility setting of "Reboot (NAND)"
- Adjusted Blex textures

Version 18.7.11
- Hotfix for broken search

Version 18.7.10
- Hotfix for broken genre view
- Added fake busy spinner to genre view

Version 18.7.9
- Reworked header bar and moved icon buttons to the right to avoid label overlapping
- Added new "Recommended" feature for library movies and TV shows (It's possible that movie and TV show hub menus have to be reseted to populate the button)
- Fixed issues with Live TV that has no EPG data
- Fixed missing widgets in Emby mixed-content nodes (most recent Emby for Kodi addon is required)
- Scale YouTube thumbnails to use the full width in wide layouts
- Minor icon and color value adjustments

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by sualfred** [comment]
Please wait with the merge. Found an issue that has to be resolved first and since it wasn't merged yet I want to get an additional feature done. Will ping you when I'm ready.

**Comment by sualfred** [comment]
@ronie 

The dependency has been merged by Rechi today and should be available shortly. You can ignore this error.

**Comment by sualfred** [comment]
@ronie 
Any reason why it's been 6 days? Or do you just missed my ping? :)

**Comment by KarellenX** [comment]
@sualfred 

ronie has been MIA for a couple of weeks. I will ping in the skinning channel if anybody can follow up.

**Comment by sualfred** [comment]
@KarellenX 

Ok, thanks. In the meantime I've pushed the version again so the recent changes are also available on the Kodi repo.

**Comment by sualfred** [comment]
Error can be ignored. Rechi merged the embuary helper updated already.

**Comment by HitcherUK** [comment]
We're looking to get more team member skinners permission to sort this out.

Thanks for being patient.

**Comment by DaVukovic** [comment]
First time starting a skin review. So please bear with me

From a first shot: 

Variables: 

Variable name `GenrePath20` exists twice and `GenrePath21` is not defined
Variable name `GenrePath30` exists twice and `GenrePath31` is not defined
Variable name `GenrePath40` exists twice and `GenrePath41` is not defined
Variable name `GenrePath44` exists twice and `GenrePath43` is not defined

I guess that unused variables and unused includes can be ignored as they don't affect the skin.

Found by luck ;) : 

In Embuary_MetaIncludes.xml you have some `$PARAP[width]` which I guess should be `$PARAM[width]` instead, no? Grepped the full skin for `PARAP` and found only 3 results all in the same file.

In DialogNumeric.xml L19 : `<orentation>` instead of `<orientation>`

In Embuary_VideoInfoDialog.xml L247/249 two times a `<right>`-tag where a single one should be enough

In:

```
DialogAddonInfo.xml
DialogPVRInfo.xml
Embuary_InfoDialog.xml
Embuary_PVRSet_View_57.xml
Embuary_VideoInfoDialog.xml
script-script.extendedinfo-DialogInfo.xml
script-script.extendedinfo-DialogVideoInfo.xml
```
wrong usage of `top` in the `<align>`-tag as per our docs only `left`, `right` and `center` should be correct, no? Ignore that if I'm wrong

In Embuary_ItemLayouts L1465 + L1470 multiple <font>-tags are in use in the same control.

In Embuary_Includes.xml L219 multiple <colordiffuse>-tags in the same control

In Embuar_Overlays.xml L140 multiple <aligny>-tags in the same control

In MyWeather.xml L81 multiple <right>-tags in the same control

Not so sure about the following. So please ignore that if I'm mistaken. You often use `orientation`, `itemgap` and `align/aligny` in group-controls. AFAICT those are only used in list- or grouplist- controls, no? If I'm correct I'm feeling very sorry that I can't provide a list of files/sections where this is the case. I just checked with SublimeText and its complaining about that. 

That's it from my side ;)

**Comment by jurialmunkey** [comment]
@DaVukovic Thanks for taking the time to do this! 
I'll also try to have a look sometime over the weekend. 

FYI - Repeat tags are fine as Kodi just uses first instance and will ignore the rest (though can be worth removing repeats for the sake of code clarity). 

Also, in a grouplist (and only a grouplist), `<align>top</align>` or `<align>bottom</align>` are both valid. I'm not sure why grouplists are different and don't use the `<aligny>` tag - I guess because alignment is dependent on orientation.

Other than what I've mentioned here, the rest of the points you raise will all need to be fixed.

**Comment by sualfred** [comment]
@DaVukovic Thanks! Most of them were simple copy pasta issues

Fore reference please take a look at the better readable commit of your mentioned issues:
https://github.com/sualfred/skin.embuary/commit/7a796fb6e53688158b5bc94b00a92086965d5231

**Comment by ronie** [comment]
sorry for the delay.

could you please remove the included .psd files?
looking good for the rest.

**Comment by sualfred** [comment]
@ronie 
Which psd files? There are none on my repo-skins fork, only on my private github.

**Comment by ronie** [comment]
apologies for the brainfart ;-)

**Pull request merged**
