### PR TITLE
[skin.featherence] 0.4.4

### PR DESCRIPTION
**Pull request by finalmakerr**
New skin for Isengard.
I hope i submitted it properly.

### CODE REVIEW

**Comment by ronie** [comment]
please squash those commits.

**Comment by finalmakerr** [comment]
the last commit is a full one.

**Comment by ronie** [comment]
sorry but i need a pull-request with a single commit. not four.

**Comment by finalmakerr** [comment]
I sent a pull request via email on Feb 14 11:48 PM, subject: [Xbmc-addons] [Git Pull] skin.featherence
Have you received it?

**Pull request closed without merging**
