### PR TITLE
[skin.copacetic] 1.0.6

### PR DESCRIPTION
**Pull request by realcopacetic**
### Description
In the merge earlier, I accidentally introduced a last-minute typo in Font.xml that causes the fonts to break in the version of this skin currently live in the Kodi repo. I have removed the code causing the issues in this patch.

### Checklist:
- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by realcopacetic** [comment]
sorry @ronie I realised I had a breaking typo in Font.xml in that last merge, as the last thing I did was comment out the fontset that needed the missing addon. But it already had some comments in the block, so commenting out the whole thing broke the XML. I've removed it. Are you able to push this update live as soon as possible please, apologies for the inconvenience.

**Comment by ronie** [comment]
sure, thanx for the quick fix!

**Comment by realcopacetic** [comment]
> sure, thanx for the quick fix!

Even though you merged it straight away I'm still seeing the old code when I install the skin from Kodi repo. Is there a delay or is it because I didn't change the version number in addon.xml?

**Comment by ronie** [comment]
ah yes, a version bump would be needed here.

while there is a delay, it's only about an hour or so iirc,
so within that period corrections can be made without a version bump.

**Comment by realcopacetic** [comment]
> ah yes, a version bump would be needed here.
> 
> while there is a delay, it's only about an hour or so iirc, so within that period corrections can be made without a version bump.

Ahh ok, let me add a version bump. Apologies for all this!

**Pull request merged**
