### PR TITLE
[skin.embuary-leia] 18.6.17

### PR DESCRIPTION
**Pull request by sualfred**
### Description
Embuary skin.

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by ronie** [comment]
nice! thanx for submitting your skin to the repo!


1) please add some screenshots to the resources folder and include those in the `<assets>` tag in your addon.xml file  (see: https://kodi.wiki/view/Skin_structure)


2) please remove these unused images:
- media/dialogs/context/bottom - Kopie.png
- media/dialogs/context/middle - Kopie.png
- media/dialogs/context/top - Kopie.png
- media/dialogs/notification/bg - Kopie.png


3) please remove the .psd files included in Embuary

**Comment by sualfred** [comment]
@ronie 

Added screenshots and removed the dead files. But there are no .psd files that I can delete :-) I already removed them for the submission.

**Comment by sualfred** [comment]
Sorry, had to change something in the last minute because a Chinese guy reported a invalid font tag issue.

**Comment by ronie** [comment]
> But there are no .psd files that I can delete :-)

ah, my bad.. sorry for the noise ;-)
should be good to go then.

one last question, if i may, are you sure you want to include the '-leia' bit in your addon id?
it will prevent the skin from being auto-updated when we release kodi v19,
assuming you'll change your addon id again the to something like skin.embuary-m*.

instead users will have to manually uninstall the old version and then install the new one.

**Comment by sualfred** [comment]
I want to use different skin IDs. It has some big plus points for maintaining. And since it's somehow the "official" Emby skin and the Emby guys only have one repo for all Kodi verisons at the moment I have to handle it in this way.

**Comment by ronie** [comment]
ok, thanx for the info!

**Pull request merged**
